version: "3.3"
services:
    server:
        build:
            context: ./
            dockerfile: ${PWD}/server/docker/development/Dockerfile
        ports:
            - "9999:8080"
        volumes:
            - ./server:/usr/src/app
        external_links:
            - mongo
        container_name: mafia-server
    game:
        build:
            context: ./
            dockerfile: ${PWD}/game/docker/development/Dockerfile
        ports:
            - "8888:8080"
        volumes:
            - ./game:/usr/src/app
        external_links:
            - mongo
        container_name: mafia-game
    client:
        build:
            context: ./
            dockerfile: ${PWD}/client/docker/development/Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app
        depends_on:
            - server
            - game
        container_name: mafia-client
        tty: true
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db
        container_name: mafia-mongo